<?php
namespace app\base;

use yii\base\InvalidRouteException;
use yii\console\Exception;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\base\Action;

class BaseController extends Controller
{
    public $rBac;

    public function init()
    {
        $this->rBac = \Yii::$app->rbac;
        parent::init(); // TODO: Change the autogenerated stub
    }

    protected function getRbac(){
        return \Yii::$app->rbac;
    }

    /**
     * @param $action Action
     * @return bool
     * @throws InvalidRouteException
     * @throws Exception
     * @throws BadRequestHttpException
     */
    public function beforeAction($action)
    {
        // redirect to auth
        if(\Yii::$app->user->isGuest){
            //throw new HttpException(401,'Need authorization');
            return \Yii::$app->runAction('/auth/login');
        }
        return parent::beforeAction($action);
    }

    /**
     * @param Action $action
     * @param mixed $result
     * @return mixed
     */
    public function afterAction($action, $result)
    {
        //$page = \Yii::$app->request->url; // так понятнее.
        //\Yii::$app->session->set('page_url',$page);

        return parent::afterAction($action, $result);
    }
}